insert into codetube.countries (id, country_name) values (1, 'Afghanistan');
insert into codetube.countries (id, country_name) values (2, 'Albania');
insert into codetube.countries (id, country_name) values (3, 'Algeria');
insert into codetube.countries (id, country_name) values (4, 'Andorra');
insert into codetube.countries (id, country_name) values (5, 'Angola');
insert into codetube.countries (id, country_name) values (6, 'Antigua and Barbuda');
insert into codetube.countries (id, country_name) values (7, 'Argentina');
insert into codetube.countries (id, country_name) values (8, 'Armenia');
insert into codetube.countries (id, country_name) values (9, 'Australia');
insert into codetube.countries (id, country_name) values (10, 'Austria');
insert into codetube.countries (id, country_name) values (11, 'Azerbaijan');
insert into codetube.countries (id, country_name) values (12, 'Bahamas');
insert into codetube.countries (id, country_name) values (13, 'Bahrain');
insert into codetube.countries (id, country_name) values (14, 'Bangladesh');
insert into codetube.countries (id, country_name) values (15, 'Barbados');
insert into codetube.countries (id, country_name) values (16, 'Belarus');
insert into codetube.countries (id, country_name) values (17, 'Belgium');
insert into codetube.countries (id, country_name) values (18, 'Belize');
insert into codetube.countries (id, country_name) values (19, 'Benin');
insert into codetube.countries (id, country_name) values (20, 'Bhutan');
insert into codetube.countries (id, country_name) values (21, 'Bolivia');
insert into codetube.countries (id, country_name) values (22, 'Bosnia and Herzegovina');
insert into codetube.countries (id, country_name) values (23, 'Botswana');
insert into codetube.countries (id, country_name) values (24, 'Brazil');
insert into codetube.countries (id, country_name) values (25, 'Brunei Darussalam');
insert into codetube.countries (id, country_name) values (26, 'Bulgaria');
insert into codetube.countries (id, country_name) values (27, 'Burkina Faso');
insert into codetube.countries (id, country_name) values (28, 'Burundi');
insert into codetube.countries (id, country_name) values (29, 'Cabo Verde');
insert into codetube.countries (id, country_name) values (30, 'Cambodia');
insert into codetube.countries (id, country_name) values (31, 'Cameroon');
insert into codetube.countries (id, country_name) values (32, 'Canada');
insert into codetube.countries (id, country_name) values (33, 'Central African Republic');
insert into codetube.countries (id, country_name) values (34, 'Chad');
insert into codetube.countries (id, country_name) values (35, 'Chile');
insert into codetube.countries (id, country_name) values (36, 'China');
insert into codetube.countries (id, country_name) values (37, 'Colombia');
insert into codetube.countries (id, country_name) values (38, 'Comoros');
insert into codetube.countries (id, country_name) values (39, 'Congo');
insert into codetube.countries (id, country_name) values (40, 'Costa Rica');
insert into codetube.countries (id, country_name) values (41, 'Ivory Coast');
insert into codetube.countries (id, country_name) values (42, 'Croatia');
insert into codetube.countries (id, country_name) values (43, 'Cuba');
insert into codetube.countries (id, country_name) values (44, 'Cyprus');
insert into codetube.countries (id, country_name) values (45, 'Czech Republic');
insert into codetube.countries (id, country_name) values (46, 'DPR of Korea');
insert into codetube.countries (id, country_name) values (47, 'DR Congo');
insert into codetube.countries (id, country_name) values (48, 'Denmark');
insert into codetube.countries (id, country_name) values (49, 'Djibouti');
insert into codetube.countries (id, country_name) values (50, 'Dominica');
insert into codetube.countries (id, country_name) values (51, 'Dominican Republic');
insert into codetube.countries (id, country_name) values (52, 'Ecuador');
insert into codetube.countries (id, country_name) values (53, 'Egypt');
insert into codetube.countries (id, country_name) values (54, 'El Salvador');
insert into codetube.countries (id, country_name) values (55, 'Equatorial Guinea');
insert into codetube.countries (id, country_name) values (56, 'Eritrea');
insert into codetube.countries (id, country_name) values (57, 'Estonia');
insert into codetube.countries (id, country_name) values (58, 'Ethiopia');
insert into codetube.countries (id, country_name) values (59, 'Fiji');
insert into codetube.countries (id, country_name) values (60, 'Finland');
insert into codetube.countries (id, country_name) values (61, 'France');
insert into codetube.countries (id, country_name) values (62, 'Gabon');
insert into codetube.countries (id, country_name) values (63, 'Gambia');
insert into codetube.countries (id, country_name) values (64, 'Georgia');
insert into codetube.countries (id, country_name) values (65, 'Germany');
insert into codetube.countries (id, country_name) values (66, 'Ghana');
insert into codetube.countries (id, country_name) values (67, 'Greece');
insert into codetube.countries (id, country_name) values (68, 'Grenada');
insert into codetube.countries (id, country_name) values (69, 'Guatemala');
insert into codetube.countries (id, country_name) values (70, 'Guinea');
insert into codetube.countries (id, country_name) values (71, 'Guinea Bissau');
insert into codetube.countries (id, country_name) values (72, 'Guyana');
insert into codetube.countries (id, country_name) values (73, 'Haiti');
insert into codetube.countries (id, country_name) values (74, 'Honduras');
insert into codetube.countries (id, country_name) values (75, 'Hungary');
insert into codetube.countries (id, country_name) values (76, 'Iceland');
insert into codetube.countries (id, country_name) values (77, 'India');
insert into codetube.countries (id, country_name) values (78, 'Indonesia');
insert into codetube.countries (id, country_name) values (79, 'Iran');
insert into codetube.countries (id, country_name) values (80, 'Iraq');
insert into codetube.countries (id, country_name) values (81, 'Ireland');
insert into codetube.countries (id, country_name) values (82, 'Israel');
insert into codetube.countries (id, country_name) values (83, 'Italy');
insert into codetube.countries (id, country_name) values (84, 'Jamaica');
insert into codetube.countries (id, country_name) values (85, 'Japan');
insert into codetube.countries (id, country_name) values (86, 'Jordan');
insert into codetube.countries (id, country_name) values (87, 'Kazakhstan');
insert into codetube.countries (id, country_name) values (88, 'Kenya');
insert into codetube.countries (id, country_name) values (89, 'Kiribati');
insert into codetube.countries (id, country_name) values (90, 'Kuwait');
insert into codetube.countries (id, country_name) values (91, 'Kyrgyzstan');
insert into codetube.countries (id, country_name) values (92, 'Laos');
insert into codetube.countries (id, country_name) values (93, 'Latvia');
insert into codetube.countries (id, country_name) values (94, 'Lebanon');
insert into codetube.countries (id, country_name) values (95, 'Lesotho');
insert into codetube.countries (id, country_name) values (96, 'Liberia');
insert into codetube.countries (id, country_name) values (97, 'Libya');
insert into codetube.countries (id, country_name) values (98, 'Liechtenstein');
insert into codetube.countries (id, country_name) values (99, 'Lithuania');
insert into codetube.countries (id, country_name) values (100, 'Luxembourg');
insert into codetube.countries (id, country_name) values (101, 'Madagascar');
insert into codetube.countries (id, country_name) values (102, 'Malawi');
insert into codetube.countries (id, country_name) values (103, 'Malaysia');
insert into codetube.countries (id, country_name) values (104, 'Maldives');
insert into codetube.countries (id, country_name) values (105, 'Mali');
insert into codetube.countries (id, country_name) values (106, 'Malta');
insert into codetube.countries (id, country_name) values (107, 'Marshall Islands');
insert into codetube.countries (id, country_name) values (108, 'Mauritania');
insert into codetube.countries (id, country_name) values (109, 'Mauritius');
insert into codetube.countries (id, country_name) values (110, 'Mexico');
insert into codetube.countries (id, country_name) values (111, 'Micronesia');
insert into codetube.countries (id, country_name) values (112, 'Monaco');
insert into codetube.countries (id, country_name) values (113, 'Mongolia');
insert into codetube.countries (id, country_name) values (114, 'Montenegro');
insert into codetube.countries (id, country_name) values (115, 'Morocco');
insert into codetube.countries (id, country_name) values (116, 'Mozambique');
insert into codetube.countries (id, country_name) values (117, 'Myanmar');
insert into codetube.countries (id, country_name) values (118, 'Namibia');
insert into codetube.countries (id, country_name) values (119, 'Nauru');
insert into codetube.countries (id, country_name) values (120, 'Nepal');
insert into codetube.countries (id, country_name) values (121, 'Netherlands');
insert into codetube.countries (id, country_name) values (122, 'New Zealand');
insert into codetube.countries (id, country_name) values (123, 'Nicaragua');
insert into codetube.countries (id, country_name) values (124, 'Niger');
insert into codetube.countries (id, country_name) values (125, 'Nigeria');
insert into codetube.countries (id, country_name) values (126, 'Norway');
insert into codetube.countries (id, country_name) values (127, 'Oman');
insert into codetube.countries (id, country_name) values (128, 'Pakistan');
insert into codetube.countries (id, country_name) values (129, 'Palau');
insert into codetube.countries (id, country_name) values (130, 'Panama');
insert into codetube.countries (id, country_name) values (131, 'Papua New Guinea');
insert into codetube.countries (id, country_name) values (132, 'Paraguay');
insert into codetube.countries (id, country_name) values (133, 'Peru');
insert into codetube.countries (id, country_name) values (134, 'Philippines');
insert into codetube.countries (id, country_name) values (135, 'Poland');
insert into codetube.countries (id, country_name) values (136, 'Portugal');
insert into codetube.countries (id, country_name) values (137, 'Qatar');
insert into codetube.countries (id, country_name) values (138, 'Republic of Korea');
insert into codetube.countries (id, country_name) values (139, 'Republic of Moldova');
insert into codetube.countries (id, country_name) values (140, 'Romania');
insert into codetube.countries (id, country_name) values (141, 'Russian Federation');
insert into codetube.countries (id, country_name) values (142, 'Rwanda');
insert into codetube.countries (id, country_name) values (143, 'Saint Kitts and Nevis');
insert into codetube.countries (id, country_name) values (144, 'Saint Lucia');
insert into codetube.countries (id, country_name) values (145, 'Saint Vincent and the Grenadines');
insert into codetube.countries (id, country_name) values (146, 'Samoa');
insert into codetube.countries (id, country_name) values (147, 'San Marino');
insert into codetube.countries (id, country_name) values (148, 'Sao Tome and Principe');
insert into codetube.countries (id, country_name) values (149, 'Saudi Arabia');
insert into codetube.countries (id, country_name) values (150, 'Senegal');
insert into codetube.countries (id, country_name) values (151, 'Serbia');
insert into codetube.countries (id, country_name) values (152, 'Seychelles');
insert into codetube.countries (id, country_name) values (153, 'Sierra Leone');
insert into codetube.countries (id, country_name) values (154, 'Singapore');
insert into codetube.countries (id, country_name) values (155, 'Slovakia');
insert into codetube.countries (id, country_name) values (156, 'Slovenia');
insert into codetube.countries (id, country_name) values (157, 'Solomon Islands');
insert into codetube.countries (id, country_name) values (158, 'Somalia');
insert into codetube.countries (id, country_name) values (159, 'South Africa');
insert into codetube.countries (id, country_name) values (160, 'South Sudan');
insert into codetube.countries (id, country_name) values (161, 'Spain');
insert into codetube.countries (id, country_name) values (162, 'Sri Lanka');
insert into codetube.countries (id, country_name) values (163, 'Sudan');
insert into codetube.countries (id, country_name) values (164, 'Suriname');
insert into codetube.countries (id, country_name) values (165, 'Swaziland');
insert into codetube.countries (id, country_name) values (166, 'Sweden');
insert into codetube.countries (id, country_name) values (167, 'Switzerland');
insert into codetube.countries (id, country_name) values (168, 'Syrian Arab Republic');
insert into codetube.countries (id, country_name) values (169, 'Tajikistan');
insert into codetube.countries (id, country_name) values (170, 'Thailand');
insert into codetube.countries (id, country_name) values (171, 'FYR Macedonia');
insert into codetube.countries (id, country_name) values (172, 'Timor-Leste');
insert into codetube.countries (id, country_name) values (173, 'Togo');
insert into codetube.countries (id, country_name) values (174, 'Tonga');
insert into codetube.countries (id, country_name) values (175, 'Trinidad and Tobago');
insert into codetube.countries (id, country_name) values (176, 'Tunisia');
insert into codetube.countries (id, country_name) values (177, 'Turkey');
insert into codetube.countries (id, country_name) values (178, 'Turkmenistan');
insert into codetube.countries (id, country_name) values (179, 'Tuvalu');
insert into codetube.countries (id, country_name) values (180, 'Uganda');
insert into codetube.countries (id, country_name) values (181, 'Ukraine');
insert into codetube.countries (id, country_name) values (182, 'United Arab Emirates');
insert into codetube.countries (id, country_name) values (183, 'United Kingdom');
insert into codetube.countries (id, country_name) values (184, 'United Republic of Tanzania');
insert into codetube.countries (id, country_name) values (185, 'Uruguay');
insert into codetube.countries (id, country_name) values (186, 'United States of America');
insert into codetube.countries (id, country_name) values (187, 'Uzbekistan');
insert into codetube.countries (id, country_name) values (188, 'Vanuatu');
insert into codetube.countries (id, country_name) values (189, 'Venezuela');
insert into codetube.countries (id, country_name) values (190, 'Viet Nam');
insert into codetube.countries (id, country_name) values (191, 'Yemen');
insert into codetube.countries (id, country_name) values (192, 'Zambia');
insert into codetube.countries (id, country_name) values (193, 'Zimbabwe');
insert into codetube.countries (id, country_name) values (194, 'Radom');
